# Generated by Django 5.0.4 on 2024-04-26 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('empid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('gender', models.CharField(choices=[('SELECT', 'Select'), ('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='SELECT', max_length=6, null=True)),
                ('mob', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('address', models.CharField(max_length=500)),
                ('l1_manager', models.CharField(max_length=10)),
                ('projid', models.CharField(max_length=50)),
                ('horizontal', models.CharField(choices=[('SELECT', 'Select'), ('ES', 'Enterprise Services'), ('IMS', 'Application Management'), ('BPS', 'Business Processes')], default='SELECT', max_length=50, null=True)),
                ('vertical', models.CharField(choices=[('SELECT', 'Select'), ('M&C', 'Manufacturing'), ('BFS', 'Banking and Financial sevices'), ('GTT', 'GTT')], default='SELECT', max_length=50, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CVAData',
            fields=[
                ('CVA_id', models.AutoField(primary_key=True, serialize=False)),
                ('CVA_description', models.CharField(max_length=500)),
                ('CVA_feedback', models.CharField(max_length=500)),
                ('empid', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CVA_data', to='pms.employeedata')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_done', models.IntegerField(null=True)),
                ('compliance_total', models.IntegerField(null=True)),
                ('empid', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_data', to='pms.employeedata')),
            ],
        ),
        migrations.CreateModel(
            name='AttData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaves_taken', models.IntegerField(null=True)),
                ('wfh_taken', models.IntegerField(null=True)),
                ('overtime', models.IntegerField(null=True)),
                ('max_working_days', models.IntegerField(null=True)),
                ('empid', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_data', to='pms.employeedata')),
            ],
        ),
        migrations.CreateModel(
            name='Appraisal',
            fields=[
                ('appraisal_id', models.AutoField(primary_key=True, serialize=False)),
                ('appraisal_date', models.DateField(blank=True, null=True)),
                ('appraisal_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('empid', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_appraisal', to='pms.employeedata')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_text', models.TextField()),
                ('empid', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='pms.employeedata')),
            ],
        ),
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('goal_id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_description', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('empid', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='pms.employeedata')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('performance_rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comments', models.TextField()),
                ('empid', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_reviews', to='pms.employeedata')),
                ('reviewer_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_reviews', to='pms.employeedata')),
            ],
        ),
        migrations.CreateModel(
            name='TSRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=15)),
                ('course_description', models.CharField(max_length=500)),
                ('percentage_completion', models.IntegerField(null=True)),
                ('empid', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TSR_data', to='pms.employeedata')),
            ],
        ),
    ]
