# Generated by Django 5.0.4 on 2024-04-25 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empid', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=500)),
                ('mob', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('l1_manager', models.CharField(max_length=10)),
                ('projid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CVAData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CVA_id', models.CharField(max_length=50)),
                ('CVA_description', models.CharField(max_length=500)),
                ('CVA_feedback', models.CharField(max_length=500)),
                ('empid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CVA_data', to='pms.employeedata')),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance_done', models.IntegerField(default=0, null=True)),
                ('compliance_left', models.IntegerField(default=0, null=True)),
                ('empid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compliance_data', to='pms.employeedata')),
            ],
        ),
        migrations.CreateModel(
            name='AttData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaves_taken', models.IntegerField(default=0, null=True)),
                ('wfh_taken', models.IntegerField(default=0, null=True)),
                ('overtime', models.IntegerField(default=0, null=True)),
                ('max_working_days', models.IntegerField(default=0, null=True)),
                ('empid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_data', to='pms.employeedata')),
            ],
        ),
        migrations.CreateModel(
            name='TSRData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_id', models.CharField(max_length=15)),
                ('course_description', models.CharField(max_length=500)),
                ('percentage_completion', models.IntegerField(default=0, null=True)),
                ('empid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TSR_data', to='pms.employeedata')),
            ],
        ),
    ]
