# Generated by Django 5.0.4 on 2024-04-25 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attdata',
            name='leaves_taken',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attdata',
            name='max_working_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attdata',
            name='overtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='attdata',
            name='wfh_taken',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compliancedata',
            name='compliance_done',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='compliancedata',
            name='compliance_left',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='tsrdata',
            name='percentage_completion',
            field=models.IntegerField(null=True),
        ),
    ]
